# HUB
# By: Alaurentino
# Version: 2.0

#------------------------ [ Title ] -----------------------
# Enable title
title-enable: true

# Tile
title: '&6&lSeja bem-vindo!'
# Sub-title
sub_title: '&2%player%&a, configure em config.yml'

# Time title. 20 = 1 second, 200 = 10 seconds...
time: 100
# Fade-In time title. 20 = 1 second, 200 = 10 seconds...
fade_in: 20
# Fade-Out time title. 20 = 1 second, 200 = 10 seconds...
fade_out: 20

# Enable tab title
tab_enable: true

# Title header
header_msg: '&aCabecalho - &6Configure'
# Title footer
footer_msg: '&6Rodape - &aConfigure'

#------------------------ [ Server MOTD ] ------------------------

# Enable ServerMOTD
MOTD_Enable: true
# Messge MOTD you server!!!
server_motd:
    one: '&3HUB Plus &6&k:&r &b&l---&8[&b OPEN BETA &8]&b--- &6&k:&r &3%version'
    two: '&r&a&lAltere as configuracoes em &r&b&lConfig.yml'
# Max player online in server
MaxPlayers: 20

# Enable icon img...
icon_enable: true
# Set location img. <name>.png... Main is img on Server/plugins/hub/server-icon.png
icon: 'plugins/HUB/server-icon.png'

#------------------------ [ Language ] ------------------------

#Default language
default_language: 'pt_BR'

#------------------------ [ World ] ------------------------

# Game mode. EX: 0 = SURVIVAL; 1 = CREATIVE; 2 = ADVENTURE
fix_gamemode:
  - '0#world'

# Disable hunger
disable_hunger_world:
  - 'world'

# Disable rain
disable_rain_world:
  - 'world'

#Disable drop item
disable_drop_item:
  - 'world'

# Protection the damage caused by fall, explosion, pvp, fire and etc...
protection:
    pvp:
      - "world"
    fall:
      - "world"
    fire:
      - "world"
    lava:
      - "world"
    drowning:
      - "world"
    suffocation:
      - "world"
    explosion:
      - "world"
    wither:
      - "world"